#!/bin/sh

# Display Bucket Card Counts
# Written in 2012 by 伴上段
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

# This handy script displays each bucket and the number of cards in it.
# The first column is the bucket number (or "New" for new cards) and the
# second column is the number of cards in the bucket.  The columns are separated
# by tabs.

usage() {
  echo "Usage: `basename $0` [-h] deck-name-no-extension"
}

if [ $# -ne 1 ]; then
  usage >&2
  exit 1
elif [ "$1" = "-h" ]; then
  usage
  exit 0
fi

oleitner -n 30 -e 20 -b decks/$1.txt decks/$1.log 1 3 7 14 30 90 180 | awk '
BEGIN { max = -1 }

{
  if ($1 > max) {
    max = $1
  }
  if ($1 in counts) {
    counts[$1] = counts[$1] + 1
  } else {
    counts[$1] = 1
  }
}

END {
  if (-1 in counts) {
    print "New\t" counts[-1]
  }
  for (n = 0; n <= max; n++) {
    if (n in counts) {
      print n "\t" counts[n]
    }
  }
}'
