#!/bin/sh

# Download Stroke Order Diagrams for All Kanji Characters in Stdin
# Written in 2012 by 伴上段
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

ret=0
for cp in `dunicode | uniquhan`; do
  ch=`echo $cp | eunicode -n`
  if [ ! -f $ch.png ]; then
    echo $ch
    curl -f -o $ch.png http://jisho.org/static/images/stroke_diagrams/${cp}_frames.png
    if [ $? -ne 0 ]; then
      rm -f $ch.png
      echo "Failed to download $ch.png" >&2
      ret=1
    fi
  fi
done
exit $ret

