#!/bin/sh

# Demote the Specified Flashcards
# Written in 2012 by 伴上段
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

usage() {
  echo "Usage: `basename $0` [-h] deck-name-no-extension id [id...]"
}

if [ $# -lt 2 ]; then
  usage >&2
  exit 1
elif [ "$1" = "-h" ]; then
  usage
  exit 0
fi

now=`./logdate`
log=decks/$1.log
shift
for fcid in $@; do
	echo "${fcid}\t${now}\t-" >>$log
done
