#!/usr/bin/gawk -f

# Transform Kanji Flashcard Lines into Readable Forms for Review Scripts
# Written in 2012 by 伴上段
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

BEGIN { FS = "\t"; }
{
	if (NF > 3 && $4 != "") {
		printf("%s", $1)
		for (i = 4; i < NF; i++) {
			printf("\t%s", $i)
		}
		printf("\n")
	} else {
		print $1 "\t" $3
	}
	printf("%s\t<img src=\"/media/sds/%s.png\">\n", $3, $3)
	system("")
}

