#!/bin/sh

# Transform Sentence Flashcard Lines into Readable Forms for Review Scripts
# Written in 2012 by 伴上段
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

awk -W interactive 'BEGIN { FS = "\t"; }
{
	firstsound = 0
	print $1 "\t" $3;
	print $4;
	#for (i = 5; i <= NF; i++) {
	#	printf("\t");
	#	if ($i == "音") {
	#		printf("%s%s", "<audio controls=\"controls\"><source src=\"media/recordings/flashcards/ロー/", $2);
	#		if (firstsound != 0) {
	#			printf("." firstsound);
	#		}
	#		printf(".wav\" type=\"audio/wav\">Your browser does not support the audio tag.</audio>");
	#		firstsound = firstsound + 1;
	#	}
	#}
	#printf("\n");
}'

