#!/bin/sh

# Add New Flashcards for the Specified Kanji
# Written in 2012 by 伴上段
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

# This adds kanji from standard input that are not in the
# specified flashcard deck file to that deck file.

usage() {
  echo "Usage: `basename $0` [-h] kanji-deck-name-no-extension"
}

if [ $# -ne 1 ]; then
  usage >&2
  exit 1
elif [ "$1" = "-h" ]; then
  usage
  exit 0
fi

cleanup() {
  rm -f $tmpfile
}

trap cleanup EXIT

tmpfile=`mktemp genkanjicards.holdings.XXXXXXXXX`
dunicode | uniquhan >$tmpfile
for kanji in `dunicode <decks/$1.txt | uniquhan | comm -2 -3 $tmpfile - | eunicode -n`; do
  echo "`nextid`	`carddate`	$kanji	" >>decks/$1.txt
done

edeck $1
