#!/bin/sh

# Automatically Generate a Card for the Specified Deck and Open the Deck
# for Editing
# Written in 2012 by 伴上段
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

usage() {
  echo "Usage: `basename $0` [-h] deck-name-no-extension card-text [card-text ...]"
}

if [ $# -eq 1 -a "$1" = "-h" ]; then
  usage
  exit 0
elif [ $# -lt 2 ]; then
  usage >&2
  exit 1
fi

deckname=$1
shift
deck=decks/$deckname.txt
while [ $# -ne 0 ]; do
  echo "`./nextid`	`./carddate`	$1	`echo $1 | dunicode | annouhan '[' ':]' | eunicode`" | tee -a $deck
  shift
done
exec edeck $deckname

