#!/bin/sh

# Download Stroke Order Diagrams for All Decks and Log Files
# Written in 2012 by 伴上段
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

cd media/sds && ( cat ../../decks/* | ../../downloadsds )
