#!/bin/sh

# Get the Next Unique Numeric ID for a New Card
# Written in 2012 by 伴上段
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

cat decks/*.txt decks/*.log | awk 'BEGIN { max = 0; }
{ val = int($1); if (val > max) { max = val; } }
END { print max + 1 }'

