#!/bin/sh

# Review Cards from the Specified Deck
# Written in 2012 by 伴上段
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

usage() {
  echo "Usage: `basename $0` [-h] deck-name-no-extension front-side-field-id back-side-field-id"
}

if [ $# -le 4 -a "$1" = "-h" ]; then
  usage
  exit 0
elif [ $# -ne 3 ]; then
  usage >&2
  exit 1
fi

cleanup() {
  rm -f $fifofile
}

trap cleanup EXIT

fifofile=$PWD/reviewsome.$$
mkfifo -m 0700 $fifofile

( oleitner -n 30 -e 20 decks/$1.txt decks/$1.log 1 3 7 14 30 90 180 >$fifofile ) &
oboeta -d -f "%Y年%m月%d日%H時%M分%S秒" $fifofile decks/$1.log $2 $3

